version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    volumes:
      - ..:/workspace
    command: sleep infinity
    networks:
      - dev-network
    depends_on:
      - redis

  service-a:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    volumes:
      - ../service-a:/workspace
    working_dir: /workspace
    ports:
      - "7000:7000"
    networks:
      - dev-network
    depends_on:
      - redis
    command: node index.js

  service-b:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    volumes:
      - ../service-b:/workspace
    working_dir: /workspace
    ports:
      - "7001:7001"
    networks:
      - dev-network
    depends_on:
      - redis
    command: node index.js

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dev-network
    command: redis-server --appendonly yes
volumes:
  redis-data:
networks:
  dev-network:
    driver: bridge